version: '3.1'

services:
  postgres-db:
    image: postgres:16.1
    container_name: influenly-database
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: influenly-backend
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_HOST=influenly-database
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - 3000:3000
    depends_on:
      - postgres-db
    volumes:
      - ./src:/app/src
